%ifarch %{arm}
# Workaround for debuginfo generator bug
# Build fails with "Bad string pointer index 1836008224 for unit name"
%define debug_package %{nil}
%endif

%define _disable_rebuild_configure 1

%define api 2.0
%define profmaj 0
%define major 1
%define libname %mklibname %{name} %{api} %{major}
%define libmonosgen %mklibname %{name}sgen %{api} %{major}
%define libmonoboehm %mklibname %{name}boehm %{api} %{major}
%define libnative %mklibname %{name}-native 0
%define libaot %mklibname %{name}-profiler-aot %{profmaj}
%define libcoverage %mklibname %{name}-profiler-coverage %{profmaj}
%define liblog %mklibname %{name}-profiler-log %{profmaj}
%define _disable_lto 1
%define libllvm %mklibname %{name}-llvm %{major}
%define devname %mklibname -d %{name}
%ifarch %arm
%define Werror_cflags %nil
%endif

%define _disable_ld_no_undefined 1

%global api_versions 2.0 4.0 4.5 4.5.1 4.5.2 4.6 4.6.1 4.6.2 4.7 4.7.1 4.7.2 4.8
%global optflags %{optflags} -I%{_includedir}/libunwind

%bcond_without bootstrap
%define monodir %{_prefix}/lib/mono

%define llvm no
%define sgen yes

%define _disable_rebuild_configure 1

%global __requires_exclude 'mono\\(\\)(.*)'

# sgen exist for ARM
#% ifnarch %{ix86} x86_64
#% define llvm no
#% define sgen no
#% endif

Summary:	Mono Runtime
Name:		mono
Version:	6.12.0.90
Release:	1
License:	GPLv2 and LGPLv2+ and MIT
Group:		Development/Other
Url:		http://www.go-mono.com/
Source0:	http://download.mono-project.com/sources/%{name}/%{name}-%{version}.tar.xz
# This key was generated by Götz Waschk <waschk@mandriva.org> on Oct 14, 2010
# by running the following command:
# sn -k mono.snk
# You should not regenerate this unless you have a really, really, really good reason.
Source1:	mono.snk
#Patch1:		mono-5.18.0.268-btls-link-pthread.patch
# https://github.com/mono/mono/issues/12632
#Patch2:		mono-5.18.0.268-workaround-arm-build-failure.patch
Source2:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-find-provides
Source3:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-find-requires
Source4:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono.attr

Patch50:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-6.6.0-ignore-reference-assemblies.patch
Patch51:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-4.2.1-ppc.patch
Patch52:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-5.10.0-find-provides.patch
Patch53:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-4.2-fix-winforms-trayicon.patch
Patch54:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-6.6.0-aarch64.patch
Patch55:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-6.6.0-roslyn-binaries.patch
Patch56:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-5.18.0-use-mcs.patch
Patch57:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-5.18.0-reference-assemblies-fix.patch
Patch58:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-5.18.0-sharpziplib-parent-path-traversal.patch
# Fix NRE bug in api-doc-tools: https://github.com/mono/api-doc-tools/pull/464
Patch59:	https://src.fedoraproject.org/rpms/mono/raw/master/f/0001-DocumentationEnumerator.cs-Declare-iface-and-ifaceMe.patch
# Replace new Csharp features with old to allow mdoc to build
# https://github.com/mono/api-doc-tools/pull/463
Patch60:	https://src.fedoraproject.org/rpms/mono/raw/master/f/0001-Replace-new-Csharp-features-with-old-ones.patch
# Reenable mdoc build. To be upstreamed after Patch 10 and 11
Patch61:	https://src.fedoraproject.org/rpms/mono/raw/master/f/0001-Reenable-mdoc.exe-build.patch
# fix issue with conflicts between i686 and x86_64 package (#1853724)
Patch62:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-6.6.0-fix-multi-arch-issue.patch
#Patch63:	https://src.fedoraproject.org/rpms/mono/raw/master/f/mono-5.18.0.268-btls-link-pthread.patch

BuildRequires:	bison
BuildRequires:	python
BuildRequires:	gettext-devel
BuildRequires:	pkgconfig(libunwind)
# for xmllint
BuildRequires:	libxml2-utils
%if %{without bootstrap}
#gw needed for mono-find-requires which needs monodis and libmono.so
BuildRequires:	pkgconfig(mono)
%endif
BuildRequires:	pkgconfig(zlib)
%if "%llvm" == "yes"
#gw mono 2.8 does not build with our llvm 2.7
BuildRequires:	llvm > 2.7
%endif
BuildRequires:	cmake ninja make
# FIXME Why isn't the correct version detected?
Provides:	mono(Mono.Cecil) = 0.10.0.0
Requires:	%{name}-2.0 = %{EVRD}
Requires:	%{name}-4.0 = %{EVRD}
Requires:	%{name}-4.5 = %{EVRD}
# gw requires by System.Drawing
Requires:	libgdiplus
# Since mono 0.91 (mdk 10.0) we can rely on included config
Provides:	mono-config
Provides:	libmono-runtime
Conflicts:	%{_lib}mono0 < 2.10.9-8
Obsoletes:	mono-compat < %{EVRD}
# Bits that existed in previous versions, but not anymore
%define libiomap %mklibname %{name}-profiler-iomap %{profmaj}
%define libsystemnative %mklibname %{name}-system-native 0
Obsoletes:	%{libiomap} < %{EVRD}

%global _use_internal_dependency_generator 0
%global __find_provides env sh -c 'filelist=($(cat)) && { printf "%s\\n" "${filelist[@]}" | grep -v 4.7.1-api | grep -v 4.5-api| /usr/lib/rpm/find-provides && printf "%s\\n" "${filelist[@]}" | grep -v 4.7.1-api | grep -v 4.5-api | prefix=%{buildroot}%{_prefix} %{buildroot}%{_bindir}/mono-find-provides; } | sort | uniq'
%global __find_requires env sh -c 'filelist=($(cat)) && { printf "%s\\n" "${filelist[@]}" | /usr/lib/rpm/find-requires && printf "%s\\n" "${filelist[@]}" | prefix=%{buildroot}%{_prefix} %{buildroot}%{_bindir}/mono-find-requires; } | sort | uniq | grep ^...'
 

%description
Mono is an implementation of the ECMA Common Language Infrastructure,
it contains both a just-in-time compiler for maximum performance, and
an interpeter.  It can also be used to run programs from the .NET
Framework.

This package contains the core of the Mono runtime including its
Virtual Machine, Just-in-time compiler, C# compiler, security tools
and libraries (corlib, XML, System.Security, System.Drawing, ZipLib,
I18N, Cairo and Mono.*).

%package doc
Summary:	Documentation for the Mono runtime
Group:		Development/Other
Requires:	mono
Buildarch:	noarch

%description doc
This package provides documentation for the Mono runtime.

%package -n %{libname}
Summary:	Library for the Mono runtime
Group:		System/Libraries

%description -n %{libname}
This package provides a shared library for the Mono runtime.

%package -n %{libnative}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Obsoletes:	%{libsystemnative} < %{EVRD}

%description -n %{libnative}
This package provides a shared library for the Mono runtime.

%package -n %{libaot}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Conflicts:	%{_lib}mono0 < 2.10.9-8

%description -n %{libaot}
This package provides a shared library for the Mono runtime.

%package -n %{libcoverage}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Conflicts:	%{_lib}mono0 < 2.10.9-8

%description -n %{libcoverage}
This package provides a shared library for the Mono runtime.

%package -n %{liblog}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Conflicts:	%{_lib}mono0 < 2.10.9-8

%description -n %{liblog}
This package provides a shared library for the Mono runtime.

%package -n %{libmonoboehm}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Conflicts:	%{_lib}mono0 < 2.10.9-8

%description -n %{libmonoboehm}
This package provides a shared library for the Mono runtime.

%if "%sgen" == "yes"
%package -n %{libmonosgen}
Summary:	Library for the Mono runtime
Group:		System/Libraries
Conflicts:	%{_lib}mono0 < 2.10.9-8

%description -n %{libmonosgen}
This package provides a shared library for the Mono runtime.
%endif

%if "%llvm" == "yes"
%package -n %{libllvm}
License:	LGPLv2
Summary:	Loadable LLVM libary for mono
Group:		System/Libraries

%description -n %{libllvm}
Loadable LLVM libary for mono.
%endif

%package -n %{devname}
Summary:	Tools required to embed the Mono runtime
Group:		Development/Other
Requires:	%{libname} = %{EVRD}
Requires:	%{libnative} = %{EVRD}
Requires:	%{libaot} = %{EVRD}
Requires:	%{libcoverage} = %{EVRD}
Requires:	%{liblog} = %{EVRD}
%ifarch %{x86_64} %{ix86} %{arm}
Requires:	%{libmonoboehm} = %{EVRD}
%endif
%if "%sgen" == "yes"
Requires:	%{libmonosgen} = %{EVRD}
%endif
%if "%llvm" == "yes"
Requires:	%{libllvm} = %{EVRD}
%endif
Requires:	mono = %{EVRD}
Requires:	mono-data = %{EVRD}
Requires:	mono-build = %{EVRD}
Requires:	mono-extras = %{EVRD}
Requires:	mono-web = %{EVRD}
Requires:	mono-locale-extras = %{EVRD}
Requires:	mono-winforms = %{EVRD}
Requires:	monodoc-core = %{EVRD}
Requires:	mono-wcf = %{EVRD}
Requires:	mono-winfxcore = %{EVRD}
Obsoletes:	%{_lib}mono-profiler-cov0 < %{EVRD}
Provides:	mono-devel = %{EVRD}
Provides:	libmono-devel = %{EVRD}
Provides:	mono(PEAPI) = 1.0.5000.0
Provides:	mono(resgen) = 1.0.5000.0
Provides:	mono-bytefx-data-mysql mono-data-firebird mono-data-sybase mono-jscript

%description -n %{devname}
Header files and libraries used to embed the Mono runtime in an application.

%package winfxcore
Summary:	Mono implementation of core WinFX APIs
Group:		Development/Other
%{expand:%(for i in %{api_versions}; do echo "Requires: %{name}-winfxcore-$i = %{EVRD}"; done)}

%description winfxcore
Mono implementation of core WinFX APIs

%package web
Summary:	ASP.NET, Remoting, and Web Services for Mono
Group:		Development/Other
Requires:	mono = %{EVRD}
%(for i in %{api_versions}; do echo "Requires: %{name}-winfxcore-$i = %{EVRD}"; done)
Obsoletes:	mono-web-compat < %{EVRD}

%description web
This package provides the ASP.NET libraries and runtime for
development of web application, web services and remoting support.

%package data
Summary:	Database connectivity for Mono
Group:		Development/Other
Requires:	mono = %{EVRD}
%(for i in %{api_versions}; do echo "Requires: %{name}-data-$i = %{EVRD}"; done)
Requires:	%{name}-data-compat = %{EVRD}

%description data
This package provides a Mono assembly to facilitate data access and
manipulation with databases, LDAP compatible directory servers and/or
XML data exchange. Beyond the ADO.NET, Novell.LDAP and
System.DirectoryServices assemblies, it also includes a command line
sql application as well as the Microsoft SQL Server and ODBC data
providers.

%files data
%{_bindir}/sqlmetal
%{_bindir}/sqlsharp
%{_mandir}/man1/sqlsharp.1*
%{monodir}/gac/IBM.Data.DB2

%package extras
Summary:	Infrastructure for running and building daemons and services
Group:		Development/Other
Requires:	mono = %{EVRD}
Provides:	mono(Mono.Messaging) = 1.0.5000.0
Provides:	mono(Mono.Messaging.RabbitMQ) = 1.0.5000.0
Provides:	mono(RabbitMQ.Client) = 1.0.5000.0
Provides:	mono(System.Configuration.Install) = 1.0.5000.0
Provides:	mono(System.Management) = 1.0.5000.0
Provides:	mono(System.Messaging) = 1.0.5000.0
Provides:	mono(System.ServiceProcess) = 1.0.5000.0
Provides:	mono(mono-service) = 1.0.5000.0

%description extras
This package provides the libary and application to run services and
daemons with Mono. It also includes stubs for the following .NET 1.1
and 2.0 assemblies: Microsoft.Vsa, System.Configuration.Install,
System.Management, System.Messaging.

%files extras
%{_bindir}/mono-service
%{_bindir}/mono-service2
%{_mandir}/man1/mono-service.1*

%package winforms
Summary:	Windows Forms implementation for Mono
Group:		Development/Other
%(for i in %{api_versions}; do echo "Requires: %{name}-winforms-$i = %{EVRD}"; done)

%description winforms
This package provides a fully managed implementation of
System.Windows.Forms, the default graphical toolkit for .NET
applications.

%files winforms


%package locale-extras
Summary:	Extra locale information for Mono
Group:		Development/Other
%(for i in %{api_versions}; do echo "Requires: %{name}-locale-extras-$i = %{EVRD}"; done)

%description locale-extras
This package contains assemblies to support I18N applications for
non-latin alphabets.

%files locale-extras

%package wcf
Summary:	Mono implementation of WCF, Windows Communication Foundation
Group:		Development/Other
%(for i in %{api_versions}; do echo "Requires: %{name}-wcf-$i = %{EVRD}"; done)

%description wcf
The Mono Project is an open development initiative that is working to
develop an open source, Unix version of the .NET development platform.
Its objective is to enable Unix developers to build and deploy
cross-platform .NET applications. The project will implement various
technologies that have been submitted to the ECMA for standardization.

Mono implementation of WCF, Windows Communication Foundation

%files wcf
%{_bindir}/svcutil

%package build
Summary:	Mono APIs needed for software development
Group:		Development/Other
%(for i in %{api_versions}; do echo "Requires: %{name}-build-$i = %{EVRD}"; done)

%description build
Mono APIs needed for software development

%files build
%{monodir}/msbuild/Current

%(
for i in %{api_versions}; do
	version="$(echo $i |cut -d. -f1)$(echo $i.0 |cut -d. -f2)$(echo $i.0.0 |cut -d. -f3)"

	cat <<EOF
%package data-$i
Summary:	Database connectivity for Mono $i API
Group:		Development/Other
Requires:	mono-2.0 = %{EVRD}

%description data-$i
This package provides a Mono assembly to facilitate data access and
manipulation with databases, LDAP compatible directory servers and/or
XML data exchange under $i API. Beyond the ADO.NET, Novell.LDAP and
System.DirectoryServices assemblies, it also includes a command line
sql application as well as the Microsoft SQL Server and ODBC data
providers.

%files data-$i
%{monodir}/$i-api/IBM.Data.DB2.dll
%{monodir}/$i-api/Novell.Directory.Ldap.dll
%{monodir}/$i-api/System.Data.DataSetExtensions.dll
%{monodir}/$i-api/System.Data.Linq.dll
%{monodir}/$i-api/System.Data.Services.dll
%{monodir}/$i-api/System.Data.dll
%{monodir}/$i-api/System.DirectoryServices.dll
%{monodir}/$i-api/System.DirectoryServices.Protocols.dll
%{monodir}/$i-api/System.EnterpriseServices.dll
%{monodir}/$i-api/System.Runtime.Serialization.dll
%{monodir}/$i-api/System.Transactions.dll
%{monodir}/$i-api/Mono.Data.Sqlite.dll
%{monodir}/$i-api/Mono.Data.Tds.dll
%{monodir}/$i-api/System.Data.OracleClient.dll
%{monodir}/$i-api/WebMatrix.Data.dll
EOF

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/System.Data.OracleClient/4.0.0.0*
%{monodir}/gac/Mono.Data.Sqlite/4.0.0.0*
%{monodir}/gac/Mono.Data.Tds/4.0.0.0*
%{monodir}/gac/Novell.Directory.Ldap/4.0.0.0*
%{monodir}/gac/System.Data.DataSetExtensions/4.0.0.0*
%{monodir}/gac/System.Data.Linq/4.0.0.0*
%{monodir}/gac/System.Data.Services/4.0.0.0*
%{monodir}/gac/System.Data/4.0.0.0*
%{monodir}/gac/System.Data.Entity/4.0.0.0*
%{monodir}/gac/System.DirectoryServices/4.0.0.0*
%{monodir}/gac/System.EnterpriseServices/4.0.0.0*
%{monodir}/gac/System.Runtime.Serialization/4.0.0.0*
%{monodir}/gac/System.Transactions/4.0.0.0*
%{monodir}/gac/WebMatrix.Data/4.0.0.0*
%{monodir}/gac/System.DirectoryServices.Protocols/4.0.0.0*
EOF
	fi

	if [ "$version" = 450 ]; then
		cat <<EOF
%{monodir}/$i/IBM.Data.DB2.dll
EOF
	fi

	if [ "$version" -ge 450 ]; then
		cat <<EOF
%{monodir}/$i-api/System.Data.Entity.dll
EOF
	fi

	cat <<EOF
%package winfxcore-$i
Summary:	Mono implementation of core WinFX APIs 2.0
Group:		Development/Other
Requires:	mono-$i = %{EVRD}

%description winfxcore-$i
Mono implementation of core WinFX APIs $i

%files winfxcore-$i
%{monodir}/$i-api/System.Data.Services.Client.dll
%{monodir}/$i-api/WindowsBase.dll*
EOF
	if [ "$i" = "4.0" ]; then
		echo '%{monodir}/gac/System.Data.Services.Client/4.0.0.0*'
		echo '%{monodir}/gac/WindowsBase/4.0.0.0*'
	fi

	cat <<EOF
%package web-$i
Summary:	ASP.NET 2.0, Remoting, and Web Services for Mono
Group:		Development/Other
Requires:	mono-$i = %{EVRD}

%description web-$i
This package provides the ASP.NET $i libraries and runtime for
development of web application, web services and remoting support.

%files web-$i
%optional %config(noreplace) %{_sysconfdir}/mono/$i/Browsers/Compat.browser
%optional %config(noreplace) %{_sysconfdir}/mono/$i/DefaultWsdlHelpGenerator.aspx
%optional %config(noreplace) %{_sysconfdir}/mono/$i/web.config
%{monodir}/$i-api/Mono.Http.dll
%{monodir}/$i-api/Microsoft.Web.Infrastructure.dll
%{monodir}/$i-api/System.ComponentModel.DataAnnotations.dll
%{monodir}/$i-api/System.Runtime.Remoting.dll
%{monodir}/$i-api/System.Runtime.Serialization.Formatters.Soap.dll
%{monodir}/$i-api/System.Web.Abstractions.dll
%{monodir}/$i-api/System.Web.DynamicData.dll
%{monodir}/$i-api/System.Web.Extensions.Design.dll
%{monodir}/$i-api/System.Web.Extensions.dll
%{monodir}/$i-api/System.Web.Mvc.dll
%{monodir}/$i-api/System.Web.Routing.dll
%{monodir}/$i-api/System.Web.Services.dll
%{monodir}/$i-api/System.Web.dll
EOF
	if [ "$i" != "2.0" ]; then
		cat <<EOF
%{monodir}/$i-api/System.ComponentModel.Composition.dll
%{monodir}/$i-api/System.Web.ApplicationServices.dll
EOF
		if [ $version -ge 450 ]; then
			cat <<EOF
%{monodir}/$i-api/System.Web.Http.SelfHost.dll
%{monodir}/$i-api/System.Web.Http.WebHost.dll
%{monodir}/$i-api/System.Web.Http.dll
%{monodir}/$i-api/System.Web.Razor.dll
%{monodir}/$i-api/System.Web.WebPages.Deployment.dll
%{monodir}/$i-api/System.Web.WebPages.Razor.dll
%{monodir}/$i-api/System.Web.WebPages.dll
EOF
		fi
	fi
	if [ "$i" = "4.0" ]; then
		cat <<EOF
%{monodir}/gac/Microsoft.Web.Infrastructure/1.0.0.0*
%{monodir}/gac/Mono.Http/4.0.0.0*
%{monodir}/gac/System.ComponentModel.Composition/4.0.0.0*
%{monodir}/gac/System.ComponentModel.DataAnnotations/4.0.0.0*
%{monodir}/gac/System.Runtime.Remoting/4.0.0.0*
%{monodir}/gac/System.Runtime.Serialization.Formatters.Soap/4.0.0.0*
%{monodir}/gac/System.Web.Abstractions/4.0.0.0*
%{monodir}/gac/System.Web.ApplicationServices/4.0.0.0*
%{monodir}/gac/System.Web.DynamicData/4.0.0.0*
%{monodir}/gac/System.Web.Extensions.Design/4.0.0.0*
%{monodir}/gac/System.Web.Extensions/4.0.0.0*
%{monodir}/gac/System.Web.Routing/4.0.0.0*
%{monodir}/gac/System.Web.Services/4.0.0.0*
%{monodir}/gac/System.Web/4.0.0.0*
EOF
	fi
	if [ "$i" = "4.5" ]; then
		cat <<EOF
%{monodir}/gac/System.Web.Http.SelfHost/4.0.0.0*
%{monodir}/gac/System.Web.Http.WebHost/4.0.0.0*
%{monodir}/gac/System.Web.Http/4.0.0.0*
%{monodir}/gac/System.Web.Mvc/3.0.0.0*
%{monodir}/gac/System.Web.Razor/2.0.0.0*
%{monodir}/gac/System.Web.WebPages*/2.0.0.0*
%{monodir}/$i/Microsoft.Web.Infrastructure.dll
EOF
	fi

	cat <<EOF
%package extras-$i
Summary:	Infrastructure for running and building daemons and services
Group:		Development/Other
Requires:	mono-$i = %{EVRD}

%description extras-$i
This package provides the libary and application to run services and
daemons with Mono $i API.

%files extras-$i
%{monodir}/$i-api/Mono.Messaging.RabbitMQ.dll
%{monodir}/$i-api/Mono.Messaging.dll
%{monodir}/$i-api/RabbitMQ.Client.dll
%{monodir}/$i-api/System.Configuration.Install.dll
%{monodir}/$i-api/System.Management.dll
%{monodir}/$i-api/System.Messaging.dll
%{monodir}/$i-api/System.ServiceProcess.dll
EOF

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/Mono.Messaging.RabbitMQ/4.0.0.0*
%{monodir}/gac/Mono.Messaging/4.0.0.0*
%{monodir}/gac/RabbitMQ.Client/4.0.0.0*
%{monodir}/gac/System.Configuration.Install/4.0.0.0*
%{monodir}/gac/System.Management/4.0.0.0*
%{monodir}/gac/System.Messaging/4.0.0.0*
%{monodir}/gac/System.Runtime.Caching/4.0.0.0*
%{monodir}/gac/System.ServiceProcess/4.0.0.0*
%{monodir}/gac/System.Xaml/4.0.0.0*
%{monodir}/gac/mono-service/4.0.0.0*
EOF
	elif [ "$version" = "450" -o "$version" = "451" -o "$version" = "452" ]; then
		cat <<EOF
%{monodir}/$i-api/System.Xaml.dll
EOF
	fi

	cat <<EOF
%package winforms-$i
Summary:	Windows Forms implementation for Mono $i API
Group:		Development/Other
Requires:	%{name}-$i = %{EVRD}

%description winforms-$i
This package provides a fully managed implementation of
System.Windows.Forms, the default graphical toolkit for .NET $i
applications.

%files winforms-$i
%{monodir}/$i-api/Accessibility.dll
%{monodir}/$i-api/Mono.WebBrowser.dll
%{monodir}/$i-api/System.Design.dll
%{monodir}/$i-api/System.Drawing.Design.dll
%{monodir}/$i-api/System.Windows.Forms.dll
EOF

	if [ "$version" -ge "400" ]; then
		cat <<EOF
%dir %{monodir}
EOF
	fi
	if [ "$version" -gt "400" ]; then
		# 4.0-api is a symlink -- hence, can't %dir it
		cat <<EOF
%dir %{monodir}/$i-api
EOF
	else
		cat <<EOF
%{monodir}/$i-api
EOF
	fi
	if [ "$version" -ge "400" ]; then
		cat <<EOF
%dir %{monodir}/gac
%dir %{monodir}/gac/Accessibility
%dir %{monodir}/gac/Mono.WebBrowser
%dir %{monodir}/gac/System.Design
%dir %{monodir}/gac/System.Drawing.Design
%dir %{monodir}/gac/System.Windows.Forms
%dir %{monodir}/gac/System.Windows.Forms.DataVisualization
%{monodir}/$i-api/System.Windows.Forms.DataVisualization.dll
EOF
	fi

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/Accessibility/4.0.0.0*
%{monodir}/gac/Mono.WebBrowser/4.0.0.0*
%{monodir}/gac/System.Design/4.0.0.0*
%{monodir}/gac/System.Drawing.Design/4.0.0.0*
%{monodir}/gac/System.Windows.Forms.DataVisualization/4.0.0.0*
%{monodir}/gac/System.Windows.Forms/4.0.0.0*
EOF
	fi

	if [ "$version" = "450" ]; then
		cat <<EOF
%{monodir}/4.5/System.Windows.dll
%{monodir}/4.5-api/System.Windows.dll
%{monodir}/gac/System.Windows/4.0.0.0*
%{monodir}/4.5/Accessibility.dll
EOF
	fi

	if [ "$version" = "451" -o "$version" = "452" ]; then
		cat <<EOF
%{monodir}/$i-api/System.Windows.dll
EOF
	fi

	cat <<EOF
%package locale-extras-$i
Summary:	Extra locale information for Mono $i API
Group:		Development/Other
Requires:	mono-$i = %{EVRD}

%description locale-extras-$i
This package contains assemblies to support I18N applications for
non-latin alphabets for Mono $i

%files locale-extras-$i
%{monodir}/$i-api/I18N.CJK.dll
%{monodir}/$i-api/I18N.MidEast.dll
%{monodir}/$i-api/I18N.Other.dll
%{monodir}/$i-api/I18N.Rare.dll
EOF

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/I18N.CJK/4.0.0.0*
%{monodir}/gac/I18N.MidEast/4.0.0.0*
%{monodir}/gac/I18N.Other/4.0.0.0*
%{monodir}/gac/I18N.Rare/4.0.0.0*
EOF
	fi

	if [ "$version" = "450" ]; then
		cat <<EOF
%{monodir}/$i/I18N.CJK.dll
%{monodir}/$i/I18N.MidEast.dll
%{monodir}/$i/I18N.Other.dll
%{monodir}/$i/I18N.Rare.dll
EOF
	fi

	cat <<EOF
%package wcf-$i
Summary:	Mono implementation of WCF, Windows Communication Foundation, API $i
Group:		Development/Other
Requires:	%{name}-$i = %{EVRD}

%description wcf-$i
Mono implementation of WCF, Windows Communication Foundation, API $i

%files wcf-$i
%{monodir}/$i-api/System.IdentityModel.Selectors.dll
%{monodir}/$i-api/System.IdentityModel.dll
%{monodir}/$i-api/System.ServiceModel.Web.dll
%{monodir}/$i-api/System.ServiceModel.dll
EOF

	if [ "$version" -ge 400 ]; then
		cat <<EOF
%{monodir}/$i-api/System.Runtime.DurableInstancing.dll
%{monodir}/$i-api/System.ServiceModel.Activation.dll
%{monodir}/$i-api/System.ServiceModel.Discovery.dll
%{monodir}/$i-api/System.ServiceModel.Routing.dll
EOF
	fi

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/System.IdentityModel.Selectors/4.0.0.0*
%{monodir}/gac/System.IdentityModel/4.0.0.0*
%{monodir}/gac/System.Runtime.DurableInstancing/4.0.0.0*
%{monodir}/gac/System.ServiceModel.Discovery/4.0.0.0*
%{monodir}/gac/System.ServiceModel.Routing/4.0.0.0*
%{monodir}/gac/System.ServiceModel.Web/4.0.0.0*
%{monodir}/gac/System.ServiceModel/4.0.0.0*
%{monodir}/gac/System.ServiceModel.Activation/4.0.0.0*
EOF
	fi

	cat <<EOF
%package build-$i
Summary:	Mono APIs needed for software development, API $i
Group:		Development/Other

%description build-$i
Mono APIs needed for software development, API $i

%files build-$i
%{monodir}/$i-api/Microsoft.Build.Framework.dll
%dir %{monodir}/gac/Microsoft.Build.Framework/
%{monodir}/$i-api/Microsoft.Build.Engine.dll
%{monodir}/$i-api/Mono.CodeContracts.dll
%dir %{monodir}/gac/Microsoft.Build.Engine/
%{monodir}/$i-api/Mono.Debugger.Soft.dll
%dir %{monodir}/gac/Mono.Debugger.Soft/
%{monodir}/$i-api/PEAPI.dll
%dir %{monodir}/gac/PEAPI/
EOF

	if [ "$version" = "200" ]; then
		cat <<EOF
%{monodir}/$i-api/Microsoft.Build.Tasks.dll
%{monodir}/$i-api/Microsoft.Build.Utilities.dll
EOF
	elif [ "$version" = "450" ]; then
		cat <<EOF
%{monodir}/gac/System.ServiceModel.Internals/0.0.0.0*
%{monodir}/$i/MSBuild
%{monodir}/$i/Microsoft.Build.*
%{monodir}/$i/Microsoft.CodeAnalysis.*
EOF
	fi

	if [ "$version" = "450" -o "$version" = "451" -o "$version" = "452" ]; then
		cat <<EOF
%{monodir}/$i-api/System.ServiceModel.Internals.dll
EOF
	fi

	if [ "$version" = 400 ]; then
		cat <<EOF
%{monodir}/gac/Microsoft.Build/4.0.0.0*
%{monodir}/gac/Microsoft.Build.Framework/4.0.0.0*
%{monodir}/gac/Microsoft.Build.Engine/4.0.0.0*
%{monodir}/gac/Microsoft.Build.Tasks.v4.0
%{monodir}/$i-api/Microsoft.Build.Tasks.v4.0.dll
%{monodir}/gac/Microsoft.Build.Utilities.v4.0
%{monodir}/$i-api/Microsoft.Build.Utilities.v4.0.dll
%{monodir}/gac/PEAPI/4.0.0.0*
%dir %{monodir}/gac/Mono.CodeContracts/
%{monodir}/gac/Mono.CodeContracts/4.0.0.0*
%{monodir}/gac/Mono.Debugger.Soft/4.0.0.0*
%{monodir}/gac/Mono.XBuild.Tasks/4.0.0.0*
EOF
	elif [ "$version" -ge 450 ]; then
		cat <<EOF
%{monodir}/$i-api/Microsoft.Build.Tasks.v4.0.dll
%{monodir}/$i-api/Microsoft.Build.Utilities.v4.0.dll
%dir %{monodir}/gac/Microsoft.Build.Tasks.Core/
%dir %{monodir}/gac/Microsoft.Build.Tasks.v12.0/
%dir %{monodir}/gac/Microsoft.Build.Utilities.Core/
%dir %{monodir}/gac/Microsoft.Build.Utilities.v12.0/
%{monodir}/gac/Microsoft.Build*/12.0.0.0*
%{monodir}/gac/Microsoft.Build*/14.0.0.0*
%{monodir}/gac/Mono.XBuild.Tasks/12.0.0.0*
%{monodir}/gac/Mono.XBuild.Tasks/14.0.0.0*
EOF
	fi

	if [ "$version" -ge 400 ]; then
		cat <<EOF
%{monodir}/$i-api/Microsoft.Build.dll
EOF
	fi

	cat <<EOF
%package $i
Summary:	$i API for mono
Group:		Development/Other
Requires:	%{name} = %{EVRD}
EOF

	if [ "$version" = "450" ]; then
		cat <<EOF
Provides:	mono(System.Collections.Immutable) = 1.2.0.0
Provides:	mono(System.IO.Compression) = 4.1.1.0
Provides:	mono(System.Security.Cryptography.Algorithms) = 4.0.0.0
Provides:	mono(System.Text.Encoding.CodePages) = 4.0.2.0
Provides:	mono(System.ValueTuple) = 4.0.1.0
Provides:	mono(System.Xml.XPath.XDocument) = 4.0.1.0
Provides:	mono(System.Diagnostics.StackTrace) = 4.0.2.0
Provides:	mono(System.Runtime.Loader) = 4.0.0.0
Provides:	mono(System) = 4.0.0.0
Provides:	mono(System.Xml) = 4.0.0.0
Provides:	mono(System.Core) = 4.0.0.0
Provides:	mono(System.Xml.Linq) = 4.0.0.0
Provides:	mono(System.Configuration) = 4.0.0.0
EOF
	fi

	cat <<EOF
%description $i
This package contains $i API for mono.

%files $i
EOF
	if [ "$version" -ne "400" ]; then
		# 4.0-api is a symlink
		cat <<EOF
%dir %{monodir}/$i-api
EOF
	fi
	cat <<EOF
%{monodir}/$i-api/Commons.Xml.Relaxng.dll
%{monodir}/$i-api/CustomMarshalers.dll
%{monodir}/$i-api/I18N.West.dll
%{monodir}/$i-api/I18N.dll
%{monodir}/$i-api/Microsoft.VisualBasic.dll
%{monodir}/$i-api/Microsoft.VisualC.dll
%{monodir}/$i-api/Mono.C5.dll
%{monodir}/$i-api/Mono.CSharp.dll
%{monodir}/$i-api/Mono.Cairo.dll
%{monodir}/$i-api/Mono.CompilerServices.SymbolWriter.dll
%{monodir}/$i-api/Mono.Management.dll
%{monodir}/$i-api/Mono.Options.dll
%{monodir}/$i-api/Mono.Parallel.dll
%{monodir}/$i-api/Mono.Posix.dll
%optional %{monodir}/$i/Mono.Posix.dll
%optional %{monodir}/$i/Microsoft.VisualBasic.dll
%optional %{monodir}/$i/Mono.C5.dll
%optional %{monodir}/$i/Mono.Options.dll
%optional %{monodir}/$i/System.Memory.dll
%optional %{monodir}/$i/System.Runtime.CompilerServices.Unsafe.dll
%optional %{monodir}/$i/System.Threading.Tasks.Extensions.dll
%{monodir}/$i-api/Mono.Security.dll
%{monodir}/$i-api/Mono.Security.Win32.dll
%{monodir}/$i-api/Mono.Simd.dll
%{monodir}/$i-api/Mono.Tasklets.dll
%{monodir}/$i-api/SMDiagnostics.dll
%{monodir}/$i-api/System.Configuration.dll
%{monodir}/$i-api/System.Core.dll
%{monodir}/$i-api/System.Drawing.dll
%{monodir}/$i-api/System.Json.dll
%{monodir}/$i-api/System.Json.Microsoft.dll
%{monodir}/$i-api/System.Net.dll
%{monodir}/$i-api/System.Net.Http.*dll
%{monodir}/$i-api/System.Numerics.Vectors.dll
%{monodir}/$i-api/System.Reactive.Core.dll
%{monodir}/$i-api/System.Reactive.Debugger.dll
%{monodir}/$i-api/System.Reactive.Experimental.dll
%{monodir}/$i-api/System.Reactive.Interfaces.dll
%{monodir}/$i-api/System.Reactive.Linq.dll
%{monodir}/$i-api/System.Reactive.Observable.Aliases.dll
%{monodir}/$i-api/System.Reactive.PlatformServices.dll
%{monodir}/$i-api/System.Reactive.Providers.dll
%{monodir}/$i-api/System.Reactive.Runtime.Remoting.dll
%{monodir}/$i-api/System.Reactive.Windows.Forms.dll
%{monodir}/$i-api/System.Reactive.Windows.Threading.dll
%{monodir}/$i-api/System.Security.dll
%{monodir}/$i-api/System.Threading.Tasks.Dataflow.dll
%{monodir}/$i-api/System.Xml.Linq.dll
%{monodir}/$i-api/System.Xml.dll
%{monodir}/$i-api/System.dll
%{monodir}/$i-api/System.Web.*.dll
%{monodir}/$i-api/cscompmgd.dll
%{monodir}/$i-api/mscorlib.dll*
EOF

	if [ "$version" -gt 200 ]; then
		cat <<EOF
%{monodir}/$i-api/Microsoft.CSharp.dll
%{monodir}/$i-api/System.Dynamic.dll
%{monodir}/$i-api/System.Numerics.dll
EOF
	fi

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/gac/Commons.Xml.Relaxng/4.0.0.0*
%{monodir}/gac/CustomMarshalers/4.0.0.0*
%{monodir}/gac/I18N.West/4.0.0.0*
%{monodir}/gac/I18N/4.0.0.0*
%{monodir}/gac/ICSharpCode.SharpZipLib/4.84.0.0*
%{monodir}/gac/Microsoft.CSharp/4.0.0.0*
%{monodir}/gac/Microsoft.VisualC/10.0.0.0*
%{monodir}/gac/Mono.CSharp/4.0.0.0*
%{monodir}/gac/Mono.Cairo/4.0.0.0*
%{monodir}/gac/Mono.CompilerServices.SymbolWriter/4.0.0.0*
%{monodir}/gac/Mono.Management/4.0.0.0*
%{monodir}/gac/Mono.Parallel/4.0.0.0*
%{monodir}/gac/Mono.Posix/4.0.0.0*
%{monodir}/gac/Mono.Security/4.0.0.0*
%{monodir}/gac/Mono.Simd/4.0.0.0*
%{monodir}/gac/Mono.Tasklets/4.0.0.0*
%{monodir}/gac/System.Configuration/4.0.0.0*
%{monodir}/gac/System.Core/4.0.0.0*
%{monodir}/gac/System.Drawing/4.0.0.0*
%{monodir}/gac/System.Dynamic/4.0.0.0*
%{monodir}/gac/System.Net*/4.0.0.0*
%{monodir}/gac/System.Numerics/4.0.0.0*
%{monodir}/gac/System.Security/4.0.0.0*
%{monodir}/gac/System.Xml.Linq/4.0.0.0*
%{monodir}/gac/System.Xml/4.0.0.0*
%{monodir}/gac/System/4.0.0.0*
%{monodir}/gac/cscompmgd/0.0.0.0*
%{monodir}/gac/System.IO.Compression.FileSystem/4.0.0.0*
%{monodir}/gac/System.IO.Compression/4.0.0.0*
%{monodir}/gac/System.Json.Microsoft/4.0.0.0*
%{monodir}/gac/System.Json/4.0.0.0*
%{monodir}/gac/System.Threading.Tasks.Dataflow/4.0.0.0*
EOF
	fi

	if [ "$version" = 450 ]; then
		cat <<EOF
%{monodir}/$i/Microsoft.CSharp.dll
%{monodir}/$i/Microsoft.CSharp.targets
%{monodir}/$i/Facades
%{monodir}/$i/I18N.dll
%{monodir}/$i/I18N.West.dll
%{monodir}/$i/Microsoft.Common.targets
%{monodir}/$i/Microsoft.Common.tasks
%{monodir}/$i/Microsoft.VisualBasic.targets
%{monodir}/$i/Microsoft.VisualC.dll
%{monodir}/$i/Mono.Btls.Interface.dll
%{monodir}/gac/Mono.Btls.Interface
%{monodir}/$i/Mono.CSharp.dll
%{monodir}/$i/Mono.Cairo.dll
%{monodir}/$i/Mono.CodeContracts.dll
%{monodir}/$i/Mono.CompilerServices.SymbolWriter.dll
%{monodir}/$i/Mono.Data.Sqlite.dll
%{monodir}/$i/Mono.Data.Tds.dll
%{monodir}/$i/Mono.Debugger.Soft.dll
%{monodir}/$i/Mono.Http.dll
%{monodir}/$i/Mono.Management.dll
%{monodir}/$i/Mono.Messaging.RabbitMQ.dll
%{monodir}/$i/Mono.Messaging.dll
%{monodir}/$i/Mono.Parallel.dll
%{monodir}/$i/Mono.Profiler.Log.dll
%{monodir}/gac/Mono.Profiler.Log
%{monodir}/$i/Mono.Security.Win32.dll
%{monodir}/gac/Mono.Security.Win32
%{monodir}/$i/Mono.Security.dll
%{monodir}/$i/Mono.Simd.dll
%{monodir}/$i/Mono.Tasklets.dll
%{monodir}/$i/Mono.WebBrowser.dll
%{monodir}/$i/Mono.XBuild.Tasks.dll
%{monodir}/$i/Novell.Directory.Ldap.dll
%{monodir}/$i/PEAPI.dll
%{monodir}/$i/RabbitMQ.Client.Apigen.exe
%{monodir}/$i/RabbitMQ.Client.Apigen.pdb
%{monodir}/$i/RabbitMQ.Client.dll
%{monodir}/$i/SMDiagnostics.dll
%{monodir}/$i/System.Collections.Immutable.dll
%{monodir}/$i/System.Collections.Immutable.dll.so
%{monodir}/$i/System.ComponentModel.Composition.dll
%{monodir}/$i/System.ComponentModel.DataAnnotations.dll
%{monodir}/$i/System.Configuration.Install.dll
%{monodir}/$i/System.Configuration.dll
%{monodir}/$i/System.Core.dll
%{monodir}/$i/System.Data.DataSetExtensions.dll
%{monodir}/$i/System.Data.Entity.dll
%{monodir}/$i/System.Data.Linq.dll
%{monodir}/$i/System.Data.OracleClient.dll
%{monodir}/$i/System.Data.Services.Client.dll
%{monodir}/$i/System.Data.Services.dll
%{monodir}/$i/System.Data.dll
%{monodir}/$i/System.Deployment.dll
%{monodir}/gac/System.Deployment
%{monodir}/$i/System.Design.dll
%{monodir}/$i/System.DirectoryServices.Protocols.dll
%{monodir}/$i/System.DirectoryServices.dll
%{monodir}/$i/System.Drawing.Design.dll
%{monodir}/$i/System.Drawing.dll
%{monodir}/$i/System.Dynamic.dll
%{monodir}/$i/System.EnterpriseServices.dll
%{monodir}/$i/System.IO.Compression.FileSystem.dll
%{monodir}/$i/System.IO.Compression.dll
%{monodir}/$i/System.IdentityModel.Selectors.dll
%{monodir}/$i/System.IdentityModel.dll
%{monodir}/$i/System.Json.Microsoft.dll
%{monodir}/$i/System.Json.dll
%{monodir}/$i/System.Management.dll
%{monodir}/$i/System.Messaging.dll
%{monodir}/$i/System.Net.Http.Formatting.dll
%{monodir}/$i/System.Net.Http.WebRequest.dll
%{monodir}/$i/System.Net.Http.dll
%{monodir}/$i/System.Net.dll
%{monodir}/$i/System.Numerics.Vectors.dll
%{monodir}/gac/System.Numerics.Vectors
%{monodir}/$i/System.Numerics.dll
%{monodir}/$i/System.Reactive.Core.dll
%{monodir}/$i/System.Reactive.Debugger.dll
%{monodir}/$i/System.Reactive.Experimental.dll
%{monodir}/$i/System.Reactive.Interfaces.dll
%{monodir}/$i/System.Reactive.Linq.dll
%{monodir}/$i/System.Reactive.Observable.Aliases.dll
%{monodir}/$i/System.Reactive.PlatformServices.dll
%{monodir}/$i/System.Reactive.Providers.dll
%{monodir}/$i/System.Reactive.Runtime.Remoting.dll
%{monodir}/$i/System.Reactive.Windows.Forms.dll
%{monodir}/$i/System.Reactive.Windows.Threading.dll
%{monodir}/$i/System.Reflection.Context.dll
%{monodir}/gac/System.Reflection.Context
%{monodir}/$i/System.Reflection.Metadata.dll
%{monodir}/$i/System.Reflection.Metadata.dll.so
%{monodir}/$i/System.Runtime.Caching.dll
%{monodir}/$i/System.Runtime.DurableInstancing.dll
%{monodir}/$i/System.Runtime.Remoting.dll
%{monodir}/$i/System.Runtime.Serialization.Formatters.Soap.dll
%{monodir}/$i/System.Runtime.Serialization.dll
%{monodir}/$i/System.Security.dll
%{monodir}/$i/System.ServiceModel.Activation.dll
%{monodir}/$i/System.ServiceModel.Discovery.dll
%{monodir}/$i/System.ServiceModel.Internals.dll
%{monodir}/$i/System.ServiceModel.Routing.dll
%{monodir}/$i/System.ServiceModel.Web.dll
%{monodir}/$i/System.ServiceModel.dll
%{monodir}/$i/System.ServiceProcess.dll
%{monodir}/$i/System.Threading.Tasks.Dataflow.dll
%{monodir}/$i/System.Transactions.dll
%{monodir}/$i/System.Web.Abstractions.dll
%{monodir}/$i/System.Web.ApplicationServices.dll
%{monodir}/$i/System.Web.DynamicData.dll
%{monodir}/$i/System.Web.Extensions.Design.dll
%{monodir}/$i/System.Web.Extensions.dll
%{monodir}/$i/System.Web.Http.SelfHost.dll
%{monodir}/$i/System.Web.Http.WebHost.dll
%{monodir}/$i/System.Web.Http.dll
%{monodir}/$i/System.Web.Mobile.dll
%{monodir}/gac/System.Web.Mobile
%{monodir}/$i/System.Web.Mvc.dll
%{monodir}/$i/System.Web.Razor.dll
%{monodir}/$i/System.Web.RegularExpressions.dll
%{monodir}/gac/System.Web.RegularExpressions
%{monodir}/$i/System.Web.Routing.dll
%{monodir}/$i/System.Web.Services.dll
%{monodir}/$i/System.Web.WebPages.Deployment.dll
%{monodir}/$i/System.Web.WebPages.Razor.dll
%{monodir}/$i/System.Web.WebPages.dll
%{monodir}/$i/System.Web.dll
%{monodir}/$i/System.Windows.Forms.DataVisualization.dll
%{monodir}/$i/System.Windows.Forms.dll
%{monodir}/$i/System.Workflow.Activities.dll
%{monodir}/gac/System.Workflow.Activities
%{monodir}/$i/System.Workflow.ComponentModel.dll
%{monodir}/gac/System.Workflow.ComponentModel
%{monodir}/$i/System.Workflow.Runtime.dll
%{monodir}/gac/System.Workflow.Runtime
%{monodir}/$i/System.Xaml.dll
%{monodir}/$i/System.Xml.Linq.dll
%{monodir}/$i/System.Xml.Serialization.dll
%{monodir}/$i/System.Xml.dll
%{monodir}/$i/System.dll
%{monodir}/$i/VBCSCompiler.exe
%{monodir}/$i/VBCSCompiler.exe.config
%{monodir}/$i/WebMatrix.Data.dll
%{monodir}/$i/WindowsBase.dll
%{monodir}/$i/al.pdb
%{monodir}/$i/browsercaps-updater.exe
%{monodir}/$i/browsercaps-updater.pdb
%{monodir}/$i/caspol.pdb
%{monodir}/$i/cccheck.pdb
%{monodir}/$i/ccrewrite.pdb
%{monodir}/$i/cert-sync.pdb
%{_mandir}/man1/cert-sync.1*
%{_mandir}/man1/cilc.1*
%{monodir}/$i/cert2spc.pdb
%{monodir}/$i/certmgr.pdb
%{monodir}/$i/chktrust.pdb
%{monodir}/$i/crlupdate.pdb
%{monodir}/$i/csc.exe
%{monodir}/$i/csc.exe.config
%{monodir}/$i/csc.exe.so
%{monodir}/$i/csc.rsp
%{monodir}/$i/csharp.pdb
%{monodir}/$i/csi.exe
%{monodir}/$i/csi.exe.config
%{monodir}/$i/csi.rsp
%{monodir}/$i/culevel.exe
%{monodir}/$i/culevel.pdb
%{monodir}/$i/disco.pdb
%{monodir}/$i/dtd2rng.pdb
%{monodir}/$i/dtd2xsd.pdb
%{monodir}/$i/gacutil.pdb
%{monodir}/$i/genxs.pdb
%{monodir}/$i/httpcfg.pdb
%{monodir}/$i/ictool.pdb
%{monodir}/$i/ikdasm.pdb
%{monodir}/$i/ilasm.pdb
%{monodir}/$i/illinkanalyzer.exe
%{monodir}/$i/illinkanalyzer.pdb
%{_mandir}/man1/illinkanalyzer.1*
%{_mandir}/man1/mdb2ppdb.1*
%{monodir}/$i/installutil.pdb
%{monodir}/$i/installvst.pdb
%{monodir}/$i/lc.pdb
%{monodir}/$i/macpack.pdb
%{monodir}/$i/makecert.pdb
%{monodir}/$i/mconfig.pdb
%{monodir}/$i/mcs.pdb
%{monodir}/$i/mdbrebase.pdb
%{monodir}/$i/mdoc.pdb
%{monodir}/$i/mkbundle.pdb
%{monodir}/$i/mod.pdb
%{monodir}/$i/mono-api-diff.exe
%{monodir}/$i/mono-api-diff.pdb
%{monodir}/$i/mono-api-html.exe
%{monodir}/$i/mono-api-html.pdb
%{monodir}/$i/mono-api-info.pdb
%{monodir}/$i/mono-cil-strip.pdb
%{monodir}/$i/mono-service.pdb
%{monodir}/$i/mono-shlib-cop.pdb
%{monodir}/$i/mono-symbolicate.pdb
%{monodir}/$i/mono-xmltool.pdb
%{monodir}/$i/monolinker.pdb
%{monodir}/$i/monop.pdb
%{monodir}/$i/mozroots.pdb
%{monodir}/$i/mscorlib.pdb
%{monodir}/$i/pdb2mdb.pdb
%{monodir}/$i/permview.pdb
%{monodir}/$i/resgen.pdb
%{monodir}/$i/secutil.pdb
%{monodir}/$i/setreg.pdb
%{monodir}/$i/sgen.pdb
%{monodir}/$i/signcode.pdb
%{monodir}/$i/sn.pdb
%{monodir}/$i/soapsuds.pdb
%{monodir}/$i/sqlmetal.pdb
%{monodir}/$i/sqlsharp.pdb
%{monodir}/$i/svcutil.pdb
%{monodir}/$i/vbc.exe
%{monodir}/$i/vbc.exe.config
%{monodir}/$i/vbc.rsp
%{monodir}/$i/wsdl.pdb
%{monodir}/$i/xbuild.pdb
%{monodir}/$i/xsd.pdb
EOF
	fi

	if [ "$version" -ge 450 ]; then
		cat <<EOF
%{monodir}/$i-api/Facades
%{monodir}/$i-api/System.IO.Compression.FileSystem.dll
%{monodir}/$i-api/System.IO.Compression.dll
%{monodir}/$i-api/System.Runtime.Caching.dll
%{monodir}/$i-api/System.Xml.Serialization.dll
EOF
	fi

	if [ "$version" = "400" ]; then
		cat <<EOF
%{monodir}/$i/mscorlib.dll
EOF
	fi

	if [ "$version" = "450" ]; then
		cat <<EOF
%{monodir}/$i/Commons.Xml.Relaxng.dll
%{monodir}/$i/CustomMarshalers.dll
%{monodir}/$i/ICSharpCode.SharpZipLib.dll
%{monodir}/$i/al.exe
%{monodir}/$i/caspol.exe
%{monodir}/$i/cccheck.exe
%{monodir}/$i/ccrewrite.exe
%{monodir}/$i/cert-sync.exe
%{monodir}/$i/cert2spc.exe
%{monodir}/$i/certmgr.exe
%{monodir}/$i/chktrust.exe
%{monodir}/$i/crlupdate.exe
%{monodir}/$i/cscompmgd.dll
%{monodir}/$i/csharp.exe
%{monodir}/$i/disco.exe
%{monodir}/$i/dtd2rng.exe
%{monodir}/$i/dtd2xsd.exe
%{monodir}/$i/gacutil.exe
%{monodir}/$i/genxs.exe
%{monodir}/$i/httpcfg.exe
%{monodir}/$i/ictool.exe
%{monodir}/$i/ikdasm.exe
%{monodir}/$i/ilasm.exe
%{monodir}/$i/installutil.exe
%{monodir}/$i/installvst.exe
%{monodir}/$i/lc.exe
%{monodir}/$i/macpack.exe
%{monodir}/$i/makecert.exe
%{monodir}/$i/mconfig.exe
%{monodir}/$i/mcs.exe
%{monodir}/$i/mcs.exe.so
%{monodir}/$i/mdbrebase.exe
%{monodir}/$i/mdoc.exe
%{monodir}/$i/mkbundle.exe
%{monodir}/$i/mod.exe
%{monodir}/$i/mono-api-info.exe
%{monodir}/$i/mono-cil-strip.exe
%{monodir}/$i/mono-service.exe
%{monodir}/$i/mono-shlib-cop.exe
%{monodir}/$i/mono-shlib-cop.exe.config
%{monodir}/$i/mono-symbolicate.exe
%{monodir}/$i/mono-xmltool.exe
%{monodir}/$i/monolinker.exe
%{monodir}/$i/monop.exe
%{monodir}/$i/mozroots.exe
%{monodir}/$i/mscorlib.dll
%{monodir}/$i/mscorlib.dll.so
%{monodir}/$i/pdb2mdb.exe
%{monodir}/$i/permview.exe
%{monodir}/$i/resgen.exe
%{monodir}/$i/secutil.exe
%{monodir}/$i/setreg.exe
%{monodir}/$i/sgen.exe
%{monodir}/$i/signcode.exe
%{monodir}/$i/sn.exe
%{monodir}/$i/soapsuds.exe
%{monodir}/$i/sqlmetal.exe
%{monodir}/$i/sqlmetal.exe.config
%{monodir}/$i/sqlsharp.exe
%{monodir}/$i/svcutil.exe
%{monodir}/$i/wsdl.exe
%{monodir}/$i/xbuild.exe
%{monodir}/$i/xbuild.exe.config
%{monodir}/$i/xbuild.rsp
%{monodir}/$i/xsd.exe
%{monodir}/gac/SMDiagnostics
%{monodir}/gac/System.Reactive*/2.2.0.0*
%{monodir}/gac/System.Reactive*/0.0.0.0*
%{monodir}/gac/System.Xml.Serialization/4.0.0.0*
EOF
	fi

	if [ "$version" -ge 460 ]; then
		cat <<EOF
%{monodir}/$i-api/System.Deployment.dll
%{monodir}/$i-api/System.Reflection.Context.dll
%{monodir}/$i-api/System.Windows.dll
%{monodir}/$i-api/System.Workflow.Activities.dll
%{monodir}/$i-api/System.Workflow.ComponentModel.dll
%{monodir}/$i-api/System.Workflow.Runtime.dll
%{monodir}/$i-api/System.Xaml.dll
EOF
		if [ "$version" -le 470 ]; then
			cat <<EOF
%{monodir}/$i-api/System.Runtime.InteropServices.RuntimeInformation.dll
%{monodir}/$i-api/System.ServiceModel.Internals.dll
EOF
		fi
	fi

	if [ "$version" -lt "471" ]; then
		cat <<EOF
%{monodir}/$i-api/ICSharpCode.SharpZipLib.dll
EOF
	fi

	if [ "$version" -gt 470 ]; then
		cat <<EOF
%{monodir}/$i-api/System.Diagnostics.Tracing.dll
EOF
	fi
done
)

# Build also has a 3.5 API that doesn't seem to exist
# for any other components
%package build-3.5
Summary:	Mono APIs needed for software development, API 3.5
Group:		Development/Other

%description build-3.5
Mono APIs needed for software development, API $i

%files build-3.5
%{monodir}/3.5-api/Microsoft.Build.Tasks.v3.5.dll
%{monodir}/3.5-api/Microsoft.Build.Utilities.v3.5.dll
%{monodir}/3.5-api/Microsoft.Build.Engine.dll
%{monodir}/3.5-api/Microsoft.Build.Framework.dll

%package web-compat
Summary:	ASP.NET, Remoting, and Web Services for Mono (Compatible package)
Group:		Development/Other
Requires:	mono-web = %{EVRD}
Provides:	mono(Mono.Http) = 1.0.5000.0
Provides:	mono(System.Runtime.Remoting) = 1.0.5000.0
Provides:	mono(System.Runtime.Serialization.Formatters.Soap) = 1.0.5000.0
Provides:	mono(System.Web) = 1.0.5000.0
Provides:	mono(System.Web.Services) = 1.0.5000.0

%description web-compat
This package provides the ASP.NET compatible requirements for
development of web application, web services and remoting support.

%package data-compat
Summary:	Database connectivity for Mono (Compatible package)
Group:		Development/Other
Requires:	mono-data = %{EVRD}
Provides:	mono(Mono.Data.Tds) = 1.0.5000.0
Provides:	mono(Novell.Directory.Ldap) = 1.0.5000.0
Provides:	mono(System.Data) = 1.0.5000.0
Provides:	mono(System.DirectoryServices) = 1.0.5000.0
Provides:	mono(System.EnterpriseServices) = 1.0.5000.0
Provides:	mono(System.Data.OracleClient) = 1.0.5000.0

%description data-compat
This package provides a Mono assembly to facilitate data access and
manipulation with databases, LDAP compatible directory servers and/or
XML data exchange. Beyond the ADO.NET, Novell.LDAP and
System.DirectoryServices assemblies, it also includes a command line
sql application as well as the Microsoft SQL Server and ODBC data
providers.

%package extras-compat
Summary:	Infrastructure for running and building daemons and services
Group:		Development/Other
Requires:	mono-extras = %{EVRD}

%description extras-compat
This package provides the libary and application to run services and
daemons.

%package winforms-compat
Summary:	Windows Forms implementation for Mono
Group:		Development/Other
Requires:	%{name}-winforms = %{EVRD}
Provides:	mono(Accessibility) = 1.0.5000.0
Provides:	mono(System.Design) = 1.0.5000.0
Provides:	mono(System.Drawing) = 1.0.5000.0
Provides:	mono(System.Drawing.Design) = 1.0.5000.0
Provides:	mono(System.Windows.Forms) = 1.0.5000.0

%description winforms-compat
This package provides a fully managed implementation of
System.Windows.Forms, the default graphical toolkit for .NET
applications.

%package locale-extras-compat
Summary:	Extra locale information for Mono
Group:		Development/Other
Requires:	mono-locale-extras = %{EVRD}
Provides:	mono(I18N.CJK) = 1.0.5000.0
Provides:	mono(I18N.MidEast) = 1.0.5000.0
Provides:	mono(I18N.Other) = 1.0.5000.0
Provides:	mono(I18N.Rare) = 1.0.5000.0

%description locale-extras-compat
This package contains assemblies to support I18N applications for
non-latin alphabets.

%package -n monodoc-core
Summary:	Monodoc-Documentation tools for C# code
Group:		Development/Other
Provides:	monodoc

%description -n monodoc-core
Monodoc-core contains documentation tools for C#.

%package aprofutil
Summary:	Mono AOT profiling tool
Group:		Development/Other

%description aprofutil
Mono AOT profiling tool

%files aprofutil
%{_bindir}/aprofutil
%{monodir}/4.5/aprofutil.exe
%{monodir}/4.5/aprofutil.pdb
%{_mandir}/man1/aprofutil.1*

%prep
%autosetup -p1

# https://github.com/mono/mono/issues/13253
find . -name "*.o" -o -name "*.so" -o -name "*.lo" |xargs rm -f

# Remove hardcoded lib directory for libMonoPosixHelper.so from the config
sed -i 's|$mono_libdir/||g' data/config.in

[ -e autogen.sh ] && NOCONFIGURE=1 ./autogen.sh

%if %{with bootstrap}
# for bootstrap, keep some binaries
#find . -name "*.dll" -not -path "./mcs/class/lib/monolite-linux/*" -not -path "./external/binary-reference-assemblies/v4.7.1/*" -print -delete
#find . -name "*.exe" -not -path "./mcs/class/lib/monolite-linux/*" -print -delete
%else
# Remove all prebuilt binaries
rm -rf mcs/class/lib/monolite-linux/*
find . -name "*.dll" -print -delete
find . -name "*.exe" -print -delete
# use the binaries from the currently installed mono
cd external/binary-reference-assemblies && mv v4.7.1 v4.7.1.tobuild && ln -s /usr/lib/mono/4.7.1-api v4.7.1 && cd -
%endif

%build

%ifarch %{aarch64}
# As of mono 5.18.0.268, clang 7.0.1:
# Build failure with clang and/or gold
%global ldflags -fuse-ld=bfd
export CC=gcc
export CXX=g++
%endif
%ifarch %{arm}
# As of mono 5.18.0.268, clang 7.0.1:
# Build failure because of bogus asm code in sha256-armv4 from btls
export CC=gcc
export CXX=g++
# Try to work around
# "mscorlib.dll.so: Bad string pointer index 1836008224 for unit name"
# while extracting debuginfo
%global ldflags %{ldflags} -fuse-ld=bfd
%endif

# cb - enable-static here as errors occur without it (warning in build that disabling static is bad)
%configure \
	--with-preview=yes \
	--with-sgen=%{sgen} \
	--enable-static \
%if "%llvm" == "yes"
	--enable-loadedllvm \
%endif

# Make sure the newly built mono tools are preferred over
# anything that may already be on the system
export MONO_BINDIR=`pwd`/runtime/_tmpinst/bin
export PATH=$MONO_BINDIR:$PATH
export LD_LIBRARY_PATH=`pwd`/mono/native/.libs

sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool

%make_build

# rebuild the reference assemblies
cd external/binary-reference-assemblies
if [ -d v4.7.1.tobuild ]; then
       rm -f v4.7.1 && mv v4.7.1.tobuild v4.7.1
fi
cd ../..
#find ./external/binary-reference-assemblies/v4.7.1/ -name \*.dll -print -delete
# v4.8 barfs with "error CS1606: Could not sign the assembly. ECMA key can only be used to delay-sign assemblies"
for i in v4.7.1 v2.0 v3.5 v4.0 v4.5 v4.5.1 v4.5.2 v4.6 v4.6.1 v4.6.2 v4.7 v4.7.2 v4.8 mono; do
	BUILD_PATH=`pwd`
	cd ./external/binary-reference-assemblies/
	MONO_PATH=$BUILD_PATH/mcs/class/lib/net_4_x-linux/ V=1 CSC="$MONO_BINDIR/csc" make -C $i
	cd ../..
done


%check
#gw unit tests in mcs/class/corlib fail
#make check

%install
# Make sure the newly built mono tools are preferred over
# anything that may already be on the system
export PATH=`pwd`/runtime/_tmpinst/bin:$PATH
export LD_LIBRARY_PATH=`pwd`/mono/native/.libs

mkdir -p %{buildroot}%{monodir}
pushd %{buildroot}%{monodir}
mkdir -p 2.0-api 3.5-api 4.5-api/Facades 4.5.1-api/Facades 4.5.2-api/Facades 4.6-api/Facades 4.6.1-api/Facades 4.6.2-api/Facades 4.7-api/Facades 4.7.1-api/Facades 4.7.2-api/Facades 4.8-api/Facades
popd
%make_install

# Remove weird dangling symlinks (probably meant by make install as a
# potential replacement for the directories they're inside rather than
# a link inside the directory?)
rm -f %{buildroot}%{monodir}/4.5-api/4.5
rm -f %{buildroot}%{monodir}/4.6-api/4.5
rm -f %{buildroot}%{monodir}/4.7-api/4.5

%find_lang mcs

mkdir -p %{buildroot}%{_sysconfdir}/pki/mono
install -p -m0644 %{SOURCE1} %{buildroot}%{_sysconfdir}/pki/mono/

# rpm helper scripts
mkdir -p %{buildroot}%{_prefix}/lib/rpm/fileattrs/
install -p -m755 %{SOURCE2} %{SOURCE3} %{buildroot}%{_prefix}/lib/rpm/
install -p -m644 %{SOURCE4} %{buildroot}%{_prefix}/lib/rpm/fileattrs/
# remove these files, we are using the files installed in /usr/lib/rpm/
rm %{buildroot}%{_bindir}/mono-find-requires
rm %{buildroot}%{_bindir}/mono-find-provides

%files -f mcs.lang
%dir %{_sysconfdir}/mono
%dir %{_sysconfdir}/mono/2.0/
%dir %{_sysconfdir}/mono/4.0/
%dir %{_sysconfdir}/mono/4.0/Browsers
%dir %{_sysconfdir}/mono/4.5/
%config(noreplace) %{_sysconfdir}/mono/2.0/machine.config
%config(noreplace) %{_sysconfdir}/mono/4.0/Browsers/Compat.browser
%config(noreplace) %{_sysconfdir}/mono/4.0/DefaultWsdlHelpGenerator.aspx
%config(noreplace) %{_sysconfdir}/mono/4.0/machine.config
%config(noreplace) %{_sysconfdir}/mono/4.0/web.config
%config(noreplace) %{_sysconfdir}/mono/4.5/machine.config
%config(noreplace) %{_sysconfdir}/mono/2.0/settings.map
%config(noreplace) %{_sysconfdir}/mono/4.0/settings.map
%config(noreplace) %{_sysconfdir}/mono/4.5/settings.map
%config  %{_sysconfdir}/mono/config
%{_bindir}/mono
%{_bindir}/mono-configuration-crypto
%{_bindir}/mono-hang-watchdog
%if "%sgen" == "yes"
%{_bindir}/mono-sgen
%{_bindir}/mono-sgen-gdb.py
%endif
%ifarch %{x86_64} %{ix86} %{arm}
%{_bindir}/mono-boehm
%endif
%{_bindir}/mono-test-install
%{_bindir}/csharp
%{_bindir}/certmgr
%{_bindir}/cert-sync
%{_bindir}/chktrust
%{_bindir}/dmcs
%{_bindir}/gacutil
%{_bindir}/gacutil2
%{_bindir}/ikdasm
%{_bindir}/mcs
%{_bindir}/mozroots
%{_bindir}/peverify
%{_bindir}/setreg
%{_bindir}/sn
# gw always check if they've got a valid soname
%{_libdir}/libMonoPosixHelper.so
%{_libdir}/libMonoSupportW.so
%{_libdir}/libikvm-native.so
#
%{_mandir}/man1/mono.1*
%{_mandir}/man1/mono-configuration-crypto.1*
%{_mandir}/man1/certmgr.1*
%{_mandir}/man1/chktrust.1*
%{_mandir}/man1/csharp.1*
%{_mandir}/man1/gacutil.1*
%{_mandir}/man1/mcs.1*
%{_mandir}/man1/mozroots.1*
%{_mandir}/man1/setreg.1*
%{_mandir}/man1/sn.1*
%{_mandir}/man5/mono-config.5*
%dir %{monodir}
%dir %{monodir}/gac/
%dir %{monodir}/3.5-api/
%{monodir}/mono-configuration-crypto
%{monodir}/gac/Mono.Cecil/
%{_prefix}/lib/rpm/fileattrs/mono.attr
%{_prefix}/lib/rpm/mono-find-provides
%{_prefix}/lib/rpm/mono-find-requires

%files doc
%doc COPYING.LIB NEWS README.md
%doc docs/*[^Makefile-Makefile.in]
%doc mcs*/docs/clr-abi.txt mcs*/docs/compiler.txt mcs*/docs/control-flow-analysis.txt

%files -n %{libname}
%{_libdir}/libmono-%{api}.so.%{major}*

%files -n %{libaot}
%{_libdir}/libmono-profiler-aot.so.%{profmaj}*

%files -n %{libcoverage}
%{_libdir}/libmono-profiler-coverage.so.%{profmaj}*

%files -n %{liblog}
%{_libdir}/libmono-profiler-log.so.%{profmaj}*

%ifarch %{x86_64} %{ix86} %{arm}
%files -n %{libmonoboehm}
%{_libdir}/libmonoboehm-%{api}.so.%{major}*
%endif

%files -n %{libmonosgen}
%{_libdir}/libmonosgen-%{api}.so.%{major}*

%files -n %{libnative}
%{_libdir}/libmono-native.so.0*

%if "%llvm" == "yes"
%files -n %{libllvm}
%{_libdir}/libmono-llvm.so.%{profmaj}*
%endif

%files -n %{devname}
%{_sysconfdir}/pki/mono/
%dir %{_includedir}/mono-%{api}/
%{_includedir}/mono-%{api}/*
%{_libdir}/libmono*.so
%{_libdir}/*.a
%{_libdir}/mono/lldb
%{_libdir}/pkgconfig/aspnetwebstack.pc
%{_libdir}/pkgconfig/cecil.pc
%{_libdir}/pkgconfig/dotnet.pc
%{_libdir}/pkgconfig/dotnet35.pc
%{_libdir}/pkgconfig/mono-cairo.pc
%{_libdir}/pkgconfig/mono-lineeditor.pc
%{_libdir}/pkgconfig/mono-options.pc
%{_libdir}/pkgconfig/mono.pc
%{_libdir}/pkgconfig/mono-2.pc
%{_libdir}/pkgconfig/monosgen-2.pc
%{_libdir}/pkgconfig/reactive.pc
%{_libdir}/pkgconfig/system.web.extensions.design_1.0.pc
%{_libdir}/pkgconfig/system.web.extensions_1.0.pc
%{_libdir}/pkgconfig/system.web.mvc.pc
%{_libdir}/pkgconfig/system.web.mvc2.pc
%{_libdir}/pkgconfig/system.web.mvc3.pc
%{_libdir}/pkgconfig/monodoc.pc
%{_libdir}/pkgconfig/wcf.pc
%{_libdir}/pkgconfig/xbuild12.pc
%{_bindir}/al
%{_bindir}/al2
%{_bindir}/caspol
%{_bindir}/cccheck
%{_bindir}/ccrewrite
%{_bindir}/cert2spc
%{_bindir}/crlupdate
%{_bindir}/csc
%{_bindir}/csi
%{_bindir}/dtd2rng
%{_bindir}/dtd2xsd
%{_bindir}/genxs
%{_bindir}/httpcfg
%{_bindir}/ilasm
%{_bindir}/illinkanalyzer
%{_bindir}/installvst
%{_bindir}/lc
#
%{_bindir}/macpack
#
%{_bindir}/makecert
%{_bindir}/mdbrebase
%{_bindir}/mkbundle
%{_bindir}/mono-api-html
%{_bindir}/mono-api-info
%{_bindir}/mono-cil-strip
%{_bindir}/mono-gdb.py
%{_bindir}/mono-heapviz
%{_bindir}/mono-package-runtime
%{_bindir}/mono-shlib-cop
%{_bindir}/mono-symbolicate
%{_bindir}/mono-xmltool
%{_bindir}/monodis
%{_bindir}/monolinker
%{_bindir}/monop
%{_bindir}/monop2
%{_bindir}/mprof-report
%{_bindir}/pedump
%{_bindir}/permview
%{_bindir}/resgen
%{_bindir}/resgen2
%{_bindir}/secutil
%{_bindir}/sgen
%{_bindir}/sgen-grep-binprot
%{_bindir}/signcode
%{_bindir}/pdb2mdb
%{_bindir}/vbc
%{_bindir}/xbuild
%{_mandir}/man1/cccheck.1*
%{_mandir}/man1/ccrewrite.1*
%{_mandir}/man1/cert2spc.1*
%{_mandir}/man1/crlupdate.1*
%{_mandir}/man1/dtd2xsd.1*
%{_mandir}/man1/genxs.1*
%{_mandir}/man1/httpcfg.1*
%{_mandir}/man1/ilasm*.1*
%{_mandir}/man1/lc.1*
#
%{_mandir}/man1/macpack.1*
#
%{_mandir}/man1/makecert.1*
%{_mandir}/man1/mkbundle.1*
%{_mandir}/man1/mono-api-info.1*
%{_mandir}/man1/mono-cil-strip.1*
%{_mandir}/man1/mono-shlib-cop.1*
%{_mandir}/man1/mono-symbolicate.1*
%{_mandir}/man1/monodis.1*
%{_mandir}/man1/monolinker.1*
%{_mandir}/man1/monop.1*
%{_mandir}/man1/mprof-report.1*
%{_mandir}/man1/permview.1*
%{_mandir}/man1/resgen.1*
%{_mandir}/man1/secutil.1*
%{_mandir}/man1/sgen.1*
%{_mandir}/man1/signcode.1*
%{_mandir}/man1/al.1*
%{_mandir}/man1/mono-xmltool.1*
%{_mandir}/man1/pdb2mdb.1*
%{_mandir}/man1/xbuild.1*
%{_prefix}/lib/mono-source-libs/
%{monodir}/xbuild/
%{monodir}/xbuild-frameworks/
%{_datadir}/mono-2.0/
%{_mandir}/man1/mono-profilers.1*

%files winfxcore

%files web
%dir %{_sysconfdir}/mono/mconfig
%config(noreplace) %{_sysconfdir}/mono/browscap.ini
%config(noreplace) %{_sysconfdir}/mono/mconfig/config.xml
%{_bindir}/disco
%{_bindir}/mconfig
%{_bindir}/soapsuds
%{_bindir}/wsdl
%{_bindir}/wsdl2
%{_bindir}/xsd
%{_mandir}/man1/disco.1*
%{_mandir}/man1/mconfig.1*
%{_mandir}/man1/soapsuds.1*
%{_mandir}/man1/wsdl.1*
%{_mandir}/man1/xsd.1*

%files winforms-compat

%files extras-compat

%files data-compat

%files locale-extras-compat

%files -n monodoc-core
%{monodir}/gac/monodoc
%{monodir}/monodoc
%{_bindir}/mdassembler
%{_bindir}/mdoc
%{_bindir}/mdoc-assemble
%{_bindir}/mdoc-export-html
%{_bindir}/mdoc-export-msxdoc
%{_bindir}/mdoc-update
%{_bindir}/mdoc-validate
%{_bindir}/mdvalidater
%{_bindir}/mod
%{_bindir}/monodocer
%{_bindir}/monodocs2html
%{_bindir}/monodocs2slashdoc
%{_prefix}/lib/monodoc
%{_mandir}/man1/mdassembler.1*
%{_mandir}/man1/mdoc-assemble.1*
%{_mandir}/man1/mdoc-export-html.1*
%{_mandir}/man1/mdoc-export-msxdoc.1*
%{_mandir}/man1/mdoc-update.1*
%{_mandir}/man1/mdoc-validate.1*
%{_mandir}/man1/mdoc.1*
%{_mandir}/man1/mdvalidater.1*
%{_mandir}/man1/monodocer.1*
%{_mandir}/man1/monodocs2html.1*
%{_mandir}/man5/mdoc.5*
